---
apiVersion: v1
kind: Service
metadata:
  name: crowi-svc
  labels:
    app: crowi-app
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: crowi-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowi-app
  labels:
    app: crowi-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crowi-app
  template:
    metadata:
      labels:
        app: crowi-app
    spec:
      containers:
        - name: crowi-svr
          command:
            - "/bin/sh"
            - "-c"
            - "./run.sh load-assets && ./run.sh serve"
          image: ghcr.io/ebiiim/crowi-docker:1.2.0
          ports:
            - containerPort: 3000
          env:
            - name: ICON_FAV_1
              value: "https://raw.githubusercontent.com/ebiiim/crowi-docker/main/assets/favicon.ico"
            - name: ICON_FAV_2
              value: "https://raw.githubusercontent.com/ebiiim/crowi-docker/main/assets/favicon-16x16.png"
            - name: ICON_FAV_3
              value: "https://raw.githubusercontent.com/ebiiim/crowi-docker/main/assets/favicon-32x32.png"
            - name: ICON_FAV_4
              value: "https://raw.githubusercontent.com/ebiiim/crowi-docker/main/assets/favicon-96x96.png"
            - name: ICON_IOS_1
              value: "https://raw.githubusercontent.com/ebiiim/crowi-docker/main/assets/apple-touch-icon.png"
            - name: ICON_IOS_2
              value: "https://raw.githubusercontent.com/ebiiim/crowi-docker/main/assets/apple-touch-icon-72x72.png"
            - name: ICON_IOS_3
              value: "https://raw.githubusercontent.com/ebiiim/crowi-docker/main/assets/apple-touch-icon-120x120.png"
            - name: ICON_IOS_4
              value: "https://raw.githubusercontent.com/ebiiim/crowi-docker/main/assets/apple-touch-icon-180x180.png"
            - name: ICON_ANDROID_1
              value: "https://raw.githubusercontent.com/ebiiim/crowi-docker/main/assets/android-chrome-192x192.png"
            - name: PORT
              value: "3000"
            - name: ELASTICSEARCH_URI
              value: http://crowi-es:9200
            - name: REDIS_URL
              value: redis://crowi-redis:6379
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: crowi-svr-secret
                  key: mongoUri
            - name: PASSWORD_SEED
              valueFrom:
                secretKeyRef:
                  name: crowi-svr-secret
                  key: passwordSeed
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          readinessProbe:
            tcpSocket:
              port: 3000
            periodSeconds: 5
